name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        pydantic-version: ["v1", "v2"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -e ".[dev,pydantic-${{ matrix.pydantic-version }},all]"
      - name: Run lint
        run: |
          poe lint
      - name: Test with pytest
        # A 250 exit status sometimes randomly comes from the coverage report black magic
        run: |
          poe test -vv
      - name: Run live redis tests
        run: |
          cd test_envs/redis-sentinel
          docker compose up -d

          export REDIS_URL="redis://$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker compose ps -q redis)):6379/0"
          export SENTINEL_HOSTS='[["'$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker compose ps -q redis-sentinel))'", 26379]]'
          poe test -vv
